[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[global]
dataFrameSerialization = "legacy"

[client]
showErrorDetails = true
